name: Override environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: example
    steps:
      - run: echo "${EXAMPLE}"
      - env:
          EXAMPLE: override
        run: echo "${EXAMPLE}"
      - run: echo "${GITHUB_ACTOR}"