name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: hoge
    steps:
      - run: echo "${BRANCH}"
      - run: echo ${{ github.ref_name }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}