name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: GITHUB_REF_NAME
    steps:
      - run: echo $BRANCH
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}